package dev.autotune.training

import dev.autotune.core.ml.AudioClass
import dev.autotune.training.SignalTools.bandPass
import dev.autotune.training.SignalTools.clip
import dev.autotune.training.SignalTools.highPass
import dev.autotune.training.SignalTools.lowPass
import dev.autotune.training.SignalTools.mixInto
import dev.autotune.training.SignalTools.normalizeTo
import dev.autotune.training.SignalTools.percussiveEnvelope
import dev.autotune.training.SignalTools.reverberate
import dev.autotune.training.SignalTools.sine
import dev.autotune.training.SignalTools.whiteNoise
import kotlin.math.PI
import kotlin.math.exp
import kotlin.math.max
import kotlin.math.min
import kotlin.math.pow
import kotlin.math.sin
import kotlin.random.Random

/** One labelled training example. */
class Clip(val samples: FloatArray, val label: AudioClass, val description: String)

/**
 * A synthetic corpus of dialogue, score and effects.
 *
 * Synthesis rather than recordings, for three reasons: the label is exact, the
 * corpus is reproducible from a seed so the committed weights can be
 * regenerated by anyone, and nothing about a user's viewing ever has to leave
 * their TV to build it.
 *
 * The generators are not trying to sound convincing to a human. They are trying
 * to reproduce the *structure* the features measure: the syllabic gaps and
 * formant motion of speech, the sustained harmonic beds and periodic pulse of
 * music, the wide flat spectra and slow envelopes of effects. Crucially, the
 * corpus includes dialogue mixed over a score, which is the case that matters
 * most and the one a naive detector gets wrong.
 */
class SyntheticCorpus(private val sampleRate: Int = 16_000) {

    fun generate(seed: Int, clips: Int, durationSeconds: Float = 4f): List<Clip> {
        val random = Random(seed)
        val length = (durationSeconds * sampleRate).toInt()
        return List(clips) { index ->
            when (index % 3) {
                0 -> speechClip(random, length)
                1 -> musicClip(random, length)
                else -> effectsClip(random, length)
            }
        }
    }

    // ---------------------------------------------------------------- speech

    /**
     * Source-filter speech: a jittered glottal pulse train through moving
     * formants, chopped into phonemes, words and sentences with real pauses.
     */
    fun speech(random: Random, length: Int): FloatArray {
        val out = FloatArray(length)
        val basePitch = if (random.nextBoolean()) {
            85.0 + random.nextDouble() * 55.0   // lower voice
        } else {
            155.0 + random.nextDouble() * 105.0 // higher voice
        }
        val speakingRate = 0.75 + random.nextDouble() * 0.6

        var position = 0
        var phonemesLeftInWord = 0
        while (position < length) {
            if (phonemesLeftInWord == 0) {
                // Gap between words, longer between sentences.
                val sentenceBreak = random.nextFloat() < 0.22f
                val gapMs = if (sentenceBreak) 320 + random.nextInt(420) else 40 + random.nextInt(110)
                position += (gapMs * sampleRate / 1000.0 / speakingRate).toInt()
                phonemesLeftInWord = 2 + random.nextInt(4)
                if (position >= length) break
            }
            phonemesLeftInWord--

            val voiced = random.nextFloat() > 0.22f
            val phonemeMs = (if (voiced) 70 + random.nextInt(130) else 45 + random.nextInt(80)) / speakingRate
            val phonemeLength = min((phonemeMs * sampleRate / 1000.0).toInt(), length - position)
            if (phonemeLength <= 32) break

            val segment = if (voiced) {
                voicedPhoneme(random, phonemeLength, basePitch)
            } else {
                unvoicedPhoneme(random, phonemeLength)
            }
            fadeEdges(segment, (0.005 * sampleRate).toInt())
            val level = (0.5 + random.nextDouble() * 0.5).toFloat() * if (voiced) 1f else 0.35f
            for (i in segment.indices) out[position + i] += segment[i] * level
            position += phonemeLength
        }

        if (random.nextFloat() < 0.7f) reverberate(out, sampleRate, 0.08f + random.nextFloat() * 0.17f, random)
        return out
    }

    private fun voicedPhoneme(random: Random, length: Int, basePitch: Double): FloatArray {
        // Three formants drawn near real vowel targets, drifting across the phoneme.
        val vowel = VOWELS[random.nextInt(VOWELS.size)]
        val next = VOWELS[random.nextInt(VOWELS.size)]
        val jitter = 0.012 + random.nextDouble() * 0.02
        val declination = -0.08 + random.nextDouble() * 0.06

        // -12 dB/octave source spectrum, as a glottal wave rolls off.
        val table = Wavetable.bandLimited(basePitch, sampleRate, maxHarmonics = 40, rolloff = 1.25)
        val excitation = FloatArray(length)
        var phase = 0.0
        for (i in 0 until length) {
            val t = i.toDouble() / length
            val f0 = basePitch * (1.0 + declination * t) * (1.0 + jitter * sin(i * 0.037))
            phase += f0 / sampleRate
            excitation[i] = table.sample(phase) * 0.35f
        }
        // Aspiration keeps it from sounding like a pure buzz and widens the spectrum.
        mixInto(excitation, whiteNoise(random, length), 0.02f)

        var result = FloatArray(length)
        for (formant in 0 until 3) {
            val start = vowel[formant]
            val end = next[formant]
            val centre = start + (end - start) * 0.5
            val q = 4.0 + formant * 2.0
            val filtered = bandPass(excitation, sampleRate, centre * (0.95 + random.nextDouble() * 0.1), q)
            val weight = FORMANT_WEIGHTS[formant]
            for (i in 0 until length) result[i] += filtered[i] * weight
        }
        result = highPass(result, sampleRate, 90.0)
        return result
    }

    private fun unvoicedPhoneme(random: Random, length: Int): FloatArray {
        val noise = whiteNoise(random, length)
        val centre = 2500.0 + random.nextDouble() * 4000.0
        val shaped = bandPass(noise, sampleRate, min(centre, sampleRate / 2.2), 0.9)
        val envelope = percussiveEnvelope(length, sampleRate, 12f, (length * 900f / sampleRate))
        for (i in 0 until length) shaped[i] *= envelope[i]
        return shaped
    }

    // ----------------------------------------------------------------- music

    /**
     * Sustained harmonic chords over a bass line and a drum pattern: continuous
     * energy, a steady pulse, and none of speech's silences.
     */
    fun music(random: Random, length: Int): FloatArray {
        val out = FloatArray(length)
        val tempo = 80 + random.nextInt(80)
        val beatSamples = (60.0 / tempo * sampleRate).toInt()
        val root = 45 + random.nextInt(12)
        val scale = if (random.nextBoolean()) MAJOR else MINOR
        val progression = IntArray(4) { scale[random.nextInt(scale.size)] }

        // Chords, held for two or four beats each.
        var position = 0
        var chordIndex = 0
        while (position < length) {
            val beats = if (random.nextFloat() < 0.6f) 4 else 2
            val chordLength = min(beatSamples * beats, length - position)
            if (chordLength <= 64) break
            val degree = progression[chordIndex % progression.size]
            chordIndex++
            val notes = intArrayOf(root + degree, root + degree + 4, root + degree + 7, root + degree + 12)
            for (note in notes) {
                val voice = harmonicVoice(random, chordLength, midiToHz(note))
                for (i in voice.indices) out[position + i] += voice[i] * 0.22f
            }
            val bass = harmonicVoice(random, chordLength, midiToHz(root + degree - 12), harmonics = 5, brightness = 0.6)
            for (i in bass.indices) out[position + i] += bass[i] * 0.35f
            position += chordLength
        }

        // Drum kit: the periodic envelope that makes the pulse feature fire.
        if (random.nextFloat() < 0.85f) {
            var beat = 0
            var beatPosition = 0
            while (beatPosition < length) {
                val remaining = length - beatPosition
                when (beat % 4) {
                    0, 2 -> addHit(out, beatPosition, kick(random, min(beatSamples, remaining)), 0.7f)
                    1, 3 -> addHit(out, beatPosition, snare(random, min(beatSamples / 2, remaining)), 0.45f)
                }
                val hatLength = min(beatSamples / 4, remaining)
                if (hatLength > 32) addHit(out, beatPosition, hat(random, hatLength), 0.18f)
                beat++
                beatPosition += beatSamples
            }
        }

        if (random.nextFloat() < 0.6f) reverberate(out, sampleRate, 0.1f + random.nextFloat() * 0.2f, random)
        return out
    }

    private fun harmonicVoice(
        random: Random,
        length: Int,
        frequency: Double,
        harmonics: Int = 8,
        brightness: Double = 1.0,
    ): FloatArray {
        val detune = 1.0 + (random.nextDouble() - 0.5) * 0.006
        val vibratoRate = 4.5 + random.nextDouble() * 2.0
        val vibratoDepth = 0.002 + random.nextDouble() * 0.003
        val table = Wavetable.bandLimited(frequency, sampleRate, harmonics, rolloff = 1.0 / brightness)
        val out = FloatArray(length)
        var phase = random.nextDouble()
        for (i in 0 until length) {
            val vibrato = 1.0 + vibratoDepth * sin(2 * PI * vibratoRate * i / sampleRate)
            phase += frequency * detune * vibrato / sampleRate
            out[i] = table.sample(phase) * 0.3f
        }
        // Slow attack and a long sustain: nothing like a syllable.
        val attack = (0.03 * sampleRate).toInt()
        val release = (0.12 * sampleRate).toInt()
        for (i in 0 until min(attack, length)) out[i] *= i.toFloat() / attack
        for (i in 0 until min(release, length)) {
            out[length - 1 - i] *= i.toFloat() / release
        }
        return out
    }

    private fun kick(random: Random, length: Int): FloatArray {
        val out = FloatArray(length)
        val envelope = percussiveEnvelope(length, sampleRate, 3f, 90f)
        var phase = 0.0
        for (i in 0 until length) {
            val f = 110.0 * exp(-i / (0.02 * sampleRate)) + 45.0
            phase += 2.0 * PI * f / sampleRate
            out[i] = (sin(phase) * envelope[i]).toFloat()
        }
        mixInto(out, lowPass(whiteNoise(random, length), sampleRate, 200.0), 0.05f)
        return out
    }

    private fun snare(random: Random, length: Int): FloatArray {
        val noise = bandPass(whiteNoise(random, length), sampleRate, 900.0, 0.7)
        val envelope = percussiveEnvelope(length, sampleRate, 2f, 70f)
        for (i in noise.indices) noise[i] *= envelope[i]
        return noise
    }

    private fun hat(random: Random, length: Int): FloatArray {
        val noise = highPass(whiteNoise(random, length), sampleRate, 5500.0)
        val envelope = percussiveEnvelope(length, sampleRate, 1f, 25f)
        for (i in noise.indices) noise[i] *= envelope[i]
        return noise
    }

    private fun addHit(target: FloatArray, offset: Int, hit: FloatArray, gain: Float) {
        val n = min(hit.size, target.size - offset)
        for (i in 0 until n) target[offset + i] += hit[i] * gain
    }

    // --------------------------------------------------------------- effects

    /** Explosions, engines, rain, crowds: broadband, aperiodic, slow-moving. */
    fun effects(random: Random, length: Int): FloatArray {
        val out = FloatArray(length)
        val layers = 1 + random.nextInt(2)
        repeat(layers) {
            when (random.nextInt(5)) {
                0 -> { // impacts and explosions
                    val hits = 1 + random.nextInt(3)
                    repeat(hits) {
                        val at = random.nextInt(max(1, length - sampleRate / 2))
                        val hitLength = min((sampleRate * (0.6 + random.nextDouble() * 1.6)).toInt(), length - at)
                        val noise = lowPass(whiteNoise(random, hitLength), sampleRate, 300.0 + random.nextDouble() * 700.0)
                        val envelope = percussiveEnvelope(hitLength, sampleRate, 4f, 250f + random.nextFloat() * 600f)
                        val thump = sine(hitLength, sampleRate, 38.0 + random.nextDouble() * 30.0)
                        for (i in 0 until hitLength) {
                            out[at + i] += (noise[i] * 0.8f + thump[i] * 0.5f) * envelope[i]
                        }
                    }
                }
                1 -> { // rain / hiss ambience
                    val noise = highPass(whiteNoise(random, length), sampleRate, 900.0 + random.nextDouble() * 2500.0)
                    mixInto(out, noise, 0.25f + random.nextFloat() * 0.2f)
                }
                2 -> { // engine / rumble
                    val base = 45.0 + random.nextDouble() * 90.0
                    val rumble = FloatArray(length)
                    var phase = 0.0
                    for (i in 0 until length) {
                        val drift = 1.0 + 0.08 * sin(2 * PI * 0.15 * i / sampleRate)
                        phase += 2.0 * PI * base * drift / sampleRate
                        rumble[i] = (sin(phase) + 0.5 * sin(phase * 2) + 0.25 * sin(phase * 3)).toFloat() * 0.3f
                    }
                    mixInto(out, rumble, 0.6f)
                    mixInto(out, lowPass(whiteNoise(random, length), sampleRate, 500.0), 0.25f)
                }
                3 -> { // crowd / room tone with slow fluctuation
                    val noise = bandPass(whiteNoise(random, length), sampleRate, 700.0, 0.5)
                    val rate = 0.3 + random.nextDouble() * 0.7
                    for (i in 0 until length) {
                        noise[i] *= (0.6 + 0.4 * sin(2 * PI * rate * i / sampleRate)).toFloat()
                    }
                    mixInto(out, noise, 0.4f)
                }
                else -> { // whoosh / sweep
                    val noise = whiteNoise(random, length)
                    val swept = FloatArray(length)
                    var state = 0f
                    for (i in 0 until length) {
                        val t = i.toDouble() / length
                        val cutoff = 0.02 + 0.4 * t
                        state += (cutoff * (noise[i] - state)).toFloat()
                        swept[i] = state * 2f
                    }
                    mixInto(out, swept, 0.5f)
                }
            }
        }
        if (random.nextFloat() < 0.5f) reverberate(out, sampleRate, 0.1f + random.nextFloat() * 0.25f, random)
        return out
    }

    // ------------------------------------------------- deliberately hard cases

    /**
     * Sung vocals: a voice, but musical.
     *
     * This is the single most confusable case. A song's vocal has the same
     * source-filter structure as dialogue, so anything keying on "is there a
     * voice" gets it wrong. What separates it is timing - notes held for
     * hundreds of milliseconds, snapped to a scale, over a continuous bed.
     */
    fun singing(random: Random, length: Int): FloatArray {
        val out = FloatArray(length)
        val root = 57 + random.nextInt(10)
        val scale = if (random.nextBoolean()) MAJOR else MINOR
        var position = 0
        while (position < length) {
            val noteLength = min((sampleRate * (0.28 + random.nextDouble() * 0.7)).toInt(), length - position)
            if (noteLength <= 64) break
            if (random.nextFloat() < 0.12f) { // breath between phrases
                position += min((sampleRate * (0.15 + random.nextDouble() * 0.35)).toInt(), length - position)
                continue
            }
            val note = root + scale[random.nextInt(scale.size)] + if (random.nextFloat() < 0.3f) 12 else 0
            val segment = sungNote(random, noteLength, midiToHz(note))
            fadeEdges(segment, (0.02 * sampleRate).toInt())
            for (i in segment.indices) out[position + i] += segment[i] * (0.6f + random.nextFloat() * 0.4f)
            position += noteLength
        }
        if (random.nextFloat() < 0.8f) reverberate(out, sampleRate, 0.12f + random.nextFloat() * 0.2f, random)
        return out
    }

    private fun sungNote(random: Random, length: Int, frequency: Double): FloatArray {
        val table = Wavetable.bandLimited(frequency, sampleRate, maxHarmonics = 40, rolloff = 1.15)
        val excitation = FloatArray(length)
        val vibratoRate = 4.5 + random.nextDouble() * 1.8
        val vibratoDepth = 0.008 + random.nextDouble() * 0.014
        var phase = random.nextDouble()
        for (i in 0 until length) {
            val vibrato = 1.0 + vibratoDepth * sin(2 * PI * vibratoRate * i / sampleRate)
            phase += frequency * vibrato / sampleRate
            excitation[i] = table.sample(phase) * 0.35f
        }
        mixInto(excitation, whiteNoise(random, length), 0.015f)
        val vowel = VOWELS[random.nextInt(VOWELS.size)]
        var result = FloatArray(length)
        for (formant in 0 until 3) {
            val filtered = bandPass(excitation, sampleRate, vowel[formant], 4.0 + formant * 2.0)
            for (i in 0 until length) result[i] += filtered[i] * FORMANT_WEIGHTS[formant]
        }
        result = highPass(result, sampleRate, 90.0)
        return result
    }

    /**
     * Effects with the periodic envelopes that would otherwise be a giveaway for
     * music: rotors, footsteps, ticking, alarms, applause.
     */
    fun periodicEffects(random: Random, length: Int): FloatArray {
        val out = FloatArray(length)
        when (random.nextInt(4)) {
            0 -> { // rotor / engine chop, 6-16 Hz
                val rate = 6.0 + random.nextDouble() * 10.0
                val period = (sampleRate / rate).toInt()
                var at = 0
                while (at < length) {
                    val hitLength = min(period, length - at)
                    val noise = lowPass(whiteNoise(random, hitLength), sampleRate, 900.0)
                    val envelope = percussiveEnvelope(hitLength, sampleRate, 3f, 25f)
                    for (i in 0 until hitLength) out[at + i] += noise[i] * envelope[i] * 0.8f
                    at += period
                }
                mixInto(out, lowPass(whiteNoise(random, length), sampleRate, 300.0), 0.3f)
            }
            1 -> { // footsteps / ticking, 1-3 Hz
                val rate = 1.0 + random.nextDouble() * 2.0
                val period = (sampleRate / rate).toInt()
                var at = 0
                while (at < length) {
                    val hitLength = min((sampleRate * 0.12).toInt(), length - at)
                    if (hitLength <= 16) break
                    val noise = bandPass(whiteNoise(random, hitLength), sampleRate, 400.0 + random.nextDouble() * 2500.0, 1.2)
                    val envelope = percussiveEnvelope(hitLength, sampleRate, 2f, 30f)
                    for (i in 0 until hitLength) out[at + i] += noise[i] * envelope[i]
                    at += period
                }
            }
            2 -> { // alarm / beeping: tonal and periodic, but not music
                val beepHz = 700.0 + random.nextDouble() * 1800.0
                val period = (sampleRate * (0.4 + random.nextDouble() * 0.8)).toInt()
                var at = 0
                while (at < length) {
                    val beepLength = min((sampleRate * 0.18).toInt(), length - at)
                    if (beepLength <= 32) break
                    val tone = sine(beepLength, sampleRate, beepHz)
                    fadeEdges(tone, (0.005 * sampleRate).toInt())
                    for (i in 0 until beepLength) out[at + i] += tone[i] * 0.5f
                    at += period
                }
            }
            else -> { // applause: dense, noise-like, no pitch at all
                val impulses = (length / sampleRate.toDouble() * (300 + random.nextInt(500))).toInt()
                repeat(impulses) {
                    val at = random.nextInt(max(1, length - 400))
                    val clapLength = min(200 + random.nextInt(200), length - at)
                    val noise = bandPass(whiteNoise(random, clapLength), sampleRate, 1500.0 + random.nextDouble() * 2500.0, 0.8)
                    val envelope = percussiveEnvelope(clapLength, sampleRate, 1f, 8f)
                    for (i in 0 until clapLength) out[at + i] += noise[i] * envelope[i] * 0.6f
                }
            }
        }
        return out
    }

    /**
     * Sparse music: solo piano, ambient pads, anything with real gaps in it.
     * Without this the model would learn "gaps mean speech".
     */
    fun sparseMusic(random: Random, length: Int): FloatArray {
        val out = FloatArray(length)
        val root = 48 + random.nextInt(14)
        val scale = if (random.nextBoolean()) MAJOR else MINOR
        var position = 0
        val sustained = random.nextBoolean()
        while (position < length) {
            val gap = if (sustained) 0 else (sampleRate * (0.1 + random.nextDouble() * 0.5)).toInt()
            position += gap
            if (position >= length) break
            val noteLength = min((sampleRate * (0.5 + random.nextDouble() * 1.6)).toInt(), length - position)
            if (noteLength <= 64) break
            val notes = if (random.nextBoolean()) 1 else 3
            repeat(notes) { voice ->
                val note = root + scale[random.nextInt(scale.size)] + voice * 4
                val voiceSamples = harmonicVoice(random, noteLength, midiToHz(note), harmonics = 10, brightness = 0.85)
                val decay = percussiveEnvelope(noteLength, sampleRate, 8f, 400f + random.nextFloat() * 900f)
                for (i in voiceSamples.indices) out[position + i] += voiceSamples[i] * decay[i] * 0.5f
            }
            position += noteLength
        }
        if (random.nextFloat() < 0.7f) reverberate(out, sampleRate, 0.15f + random.nextFloat() * 0.25f, random)
        return out
    }

    /**
     * Playback-chain damage: speaker EQ tilt, broadcast compression, a noise
     * floor and the odd bit of clipping. Features measured on a pristine mix are
     * not the features a TV produces.
     */
    private fun degrade(samples: FloatArray, random: Random) {
        if (random.nextFloat() < 0.7f) {
            val tilt = -6.0 + random.nextDouble() * 12.0
            val filter = dev.autotune.core.dsp.Biquad.lowShelf(sampleRate, 250.0, tilt)
            for (i in samples.indices) samples[i] = filter.process(samples[i])
        }
        if (random.nextFloat() < 0.5f) {
            val filter = dev.autotune.core.dsp.Biquad.peaking(
                sampleRate,
                1200.0 + random.nextDouble() * 3000.0,
                1.0,
                -5.0 + random.nextDouble() * 10.0,
            )
            for (i in samples.indices) samples[i] = filter.process(samples[i])
        }
        if (random.nextFloat() < 0.45f) compress(samples, random)
        // Most sources carry a noise floor, but a clean digital master has true
        // silence between scenes; the model has to cope with both.
        if (random.nextFloat() < 0.7f) {
            val noiseLevel = 10.0.pow((-70.0 + random.nextDouble() * 25.0) / 20.0).toFloat()
            mixInto(samples, whiteNoise(random, samples.size), noiseLevel)
        }
    }

    /** Crude broadcast-style compressor, applied to some clips before analysis. */
    private fun compress(samples: FloatArray, random: Random) {
        val threshold = 10.0.pow((-24.0 + random.nextDouble() * 10.0) / 20.0).toFloat()
        val ratio = 2f + random.nextFloat() * 4f
        val attack = exp(-1.0 / (0.005 * sampleRate)).toFloat()
        val release = exp(-1.0 / (0.15 * sampleRate)).toFloat()
        var envelope = 0f
        for (i in samples.indices) {
            val level = kotlin.math.abs(samples[i])
            envelope = if (level > envelope) attack * envelope + (1 - attack) * level
            else release * envelope + (1 - release) * level
            if (envelope > threshold) {
                val over = envelope / threshold
                val gain = over.pow(1f / ratio - 1f)
                samples[i] *= gain
            }
        }
    }

    // -------------------------------------------------------------- mixtures

    private fun speechClip(random: Random, length: Int): Clip {
        val speech = speech(random, length)
        normalizeTo(speech, -20f)
        val roll = random.nextFloat()
        val description: String
        when {
            roll < 0.20f -> description = "speech"
            roll < 0.55f -> {
                // Dialogue over a score, mixed from comfortable down to barely
                // above it. This is the case the whole app exists for.
                val bed = if (random.nextBoolean()) music(random, length) else sparseMusic(random, length)
                normalizeTo(bed, -20f - (3f + random.nextFloat() * 13f))
                mixInto(speech, bed, 1f)
                description = "speech+music"
            }
            roll < 0.75f -> {
                val bed = effects(random, length)
                normalizeTo(bed, -20f - (3f + random.nextFloat() * 13f))
                mixInto(speech, bed, 1f)
                description = "speech+effects"
            }
            roll < 0.90f -> {
                val bed = periodicEffects(random, length)
                normalizeTo(bed, -20f - (4f + random.nextFloat() * 12f))
                mixInto(speech, bed, 1f)
                description = "speech+crowd"
            }
            else -> {
                // Broadcast and phone dialogue is routinely band-limited.
                lowPass(highPass(speech, sampleRate, 180.0), sampleRate, 3600.0).copyInto(speech)
                description = "speech-bandlimited"
            }
        }
        return finish(speech, AudioClass.SPEECH, description, random)
    }

    private fun musicClip(random: Random, length: Int): Clip {
        val roll = random.nextFloat()
        val music: FloatArray
        val description: String
        when {
            roll < 0.28f -> {
                music = music(random, length)
                description = "music"
            }
            roll < 0.53f -> {
                // A song: vocals on top of the band. Voice-like, but musical.
                music = music(random, length)
                normalizeTo(music, -18f)
                val vocal = singing(random, length)
                normalizeTo(vocal, -18f + (random.nextFloat() * 6f - 2f))
                mixInto(music, vocal, 1f)
                description = "music+vocals"
            }
            roll < 0.63f -> {
                music = singing(random, length)
                description = "vocals-only"
            }
            roll < 0.83f -> {
                // Sparse music has speech-like gaps; without it the model would
                // decide that silence between events means dialogue.
                music = sparseMusic(random, length)
                description = "music-sparse"
            }
            else -> {
                music = music(random, length)
                normalizeTo(music, -18f)
                val bed = effects(random, length)
                normalizeTo(bed, -18f - (4f + random.nextFloat() * 12f))
                mixInto(music, bed, 1f)
                description = "music+effects"
            }
        }
        normalizeTo(music, -18f)
        if (random.nextFloat() < 0.25f) {
            // Dialogue buried under the music is still music, and still wants
            // pulling down.
            val voice = speech(random, length)
            normalizeTo(voice, -18f - (10f + random.nextFloat() * 10f))
            mixInto(music, voice, 1f)
        }
        return finish(music, AudioClass.MUSIC, description, random)
    }

    private fun effectsClip(random: Random, length: Int): Clip {
        val roll = random.nextFloat()
        val effects: FloatArray
        val description: String
        when {
            roll < 0.40f -> {
                effects = effects(random, length)
                description = "effects"
            }
            roll < 0.75f -> {
                // Rotors, footsteps and alarms are periodic without being music.
                effects = periodicEffects(random, length)
                description = "effects-periodic"
            }
            roll < 0.90f -> {
                effects = effects(random, length)
                normalizeTo(effects, -19f)
                val bed = sparseMusic(random, length)
                normalizeTo(bed, -19f - (6f + random.nextFloat() * 10f))
                mixInto(effects, bed, 1f)
                description = "effects+quiet-music"
            }
            else -> {
                effects = effects(random, length)
                normalizeTo(effects, -19f)
                val distant = speech(random, length)
                normalizeTo(distant, -19f - (14f + random.nextFloat() * 10f))
                mixInto(effects, distant, 1f)
                description = "effects+distant-speech"
            }
        }
        return finish(effects, AudioClass.EFFECTS, description, random)
    }

    /**
     * Randomises absolute level over a 25 dB range so the model cannot learn the
     * shortcut "loud means music" - at playback time the absolute level depends
     * on the TV's volume knob, not on the content.
     */
    private fun finish(samples: FloatArray, label: AudioClass, description: String, random: Random): Clip {
        degrade(samples, random)
        normalizeTo(samples, -32f + random.nextFloat() * 25f)
        clip(samples)
        return Clip(samples, label, description)
    }

    private fun fadeEdges(samples: FloatArray, fadeSamples: Int) {
        val fade = min(fadeSamples, samples.size / 2)
        for (i in 0 until fade) {
            val factor = i.toFloat() / fade
            samples[i] *= factor
            samples[samples.size - 1 - i] *= factor
        }
    }

    private fun midiToHz(note: Int): Double = 440.0 * 2.0.pow((note - 69) / 12.0)

    private companion object {
        /** F1/F2/F3 targets for a spread of vowels, in Hz. */
        val VOWELS = arrayOf(
            doubleArrayOf(700.0, 1220.0, 2600.0),  // /a/
            doubleArrayOf(400.0, 2000.0, 2550.0),  // /e/
            doubleArrayOf(280.0, 2250.0, 2900.0),  // /i/
            doubleArrayOf(450.0, 800.0, 2830.0),   // /o/
            doubleArrayOf(325.0, 700.0, 2530.0),   // /u/
            doubleArrayOf(600.0, 1170.0, 2400.0),  // schwa-ish
        )
        val FORMANT_WEIGHTS = floatArrayOf(1f, 0.6f, 0.35f)
        val MAJOR = intArrayOf(0, 2, 4, 5, 7, 9, 11)
        val MINOR = intArrayOf(0, 2, 3, 5, 7, 8, 10)
    }
}
